# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/miguelhmc9@gmail.com/global_populationData/notebooks/New Pipeline 2025-10-14 11:35")

# COMMAND ----------

df_global = spark.read.table("workspace.default.global_population_stats")
display(df_global)
